# .github/workflows/build.yml
# Okay, for real this time! The simple, clean, and correct way!

name: Build & Release Package Builder

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # Step 1: Check out your code
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      # This will now use the yarn version from your .yarnrc.yml file
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Step 4: Build the application for the specific OS
      # This is the big fix! We run a specific command for each OS.
      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: yarn dist:win
      
      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        run: yarn dist:mac

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn dist:linux
      
      # Step 5: Upload the finished product!
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-builder-${{ matrix.os }}
          path: dist/
