# .github/workflows/build.yml
# Okay, we're telling the robot to not give up so easily this time!

name: Build & Release Package Builder

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    
    runs-on: ${{ matrix.os }}
    strategy:
      # This is the new magic! It tells GitHub to let all jobs finish,
      # even if one of them fails. So we can see the real error for each one!
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # Step 1: Check out your code
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Force the correct Yarn version!
      - name: Install and set the correct Yarn version
        run: |
          npm install -g yarn@4.9.2
          corepack enable

      # Step 4: Install dependencies using the correct Yarn
      - name: Install dependencies
        run: yarn install --immutable

      # Step 5: Build the distributable files!
      - name: Build application
        run: yarn dist
      
      # Step 6: Upload the finished product!
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-builder-${{ matrix.os }}
          path: dist/
