# .github/workflows/build.yml
# Our magical recipe, now with the fix to make the robot happy!

name: Build & Release Package Builder

# This tells the robot WHEN to run.
# It runs every time you push code to the 'main' branch.
on:
  push:
    branches: [ "main" ]

jobs:
  # This is the name of our job, you can call it whatever you want!
  build-and-release:
    
    # This says "please run this job on a Windows, macOS, AND Linux computer!"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # Step 1: Check out your code from GitHub
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # Step 3: Enable Corepack! This is the magic fix!
      - name: Enable Corepack to use the correct Yarn version
        run: corepack enable

      # Step 4: Install all the app's dependencies
      - name: Install dependencies
        run: yarn install

      # Step 5: Build the distributable files!
      - name: Build application
        run: yarn dist
      
      # Step 6: Upload the finished product!
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-builder-${{ matrix.os }}
          path: dist/
