# .github/workflows/build.yml
# Okay, this is the one! Using the official, most robust way to set the Yarn version!

name: Build & Release Package Builder

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # Step 1: Check out your code
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js. We won't try to cache here.
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Enable Corepack & Set Yarn Version
      # By running this in its own step with bash, we ensure it's set up
      # correctly before we try to install anything.
      - name: Enable Corepack and Set Yarn Version
        run: corepack enable && yarn set version 4.9.2
        shell: bash

      # Step 4: Install dependencies using the now-correct Yarn
      - name: Install dependencies
        run: yarn install --immutable

      # Step 5: Build the distributable files!
      - name: Build application
        run: yarn dist
      
      # Step 6: Upload the finished product!
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-builder-${{ matrix.os }}
          path: dist/
