# .github/workflows/build.yml
# Okay, new plan! We're going to do this the simple, clean, and CORRECT way!

name: Build & Release Package Builder

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-release:
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      # Step 1: Check out your code
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and Yarn (The RIGHT Way!)
      # This single step will:
      #  - Install Node.js v18
      #  - Automatically enable Corepack
      #  - Read your package.json and set up the correct Yarn version (4.9.2!)
      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      # Step 3: Install dependencies
      # This will now use the correct version of Yarn!
      - name: Install dependencies
        run: yarn install --immutable

      # Step 4: Build the distributable files!
      # We just run 'yarn dist'. The matrix makes sure it only builds
      # for the OS it's currently running on (Windows builds .exe, etc.)
      - name: Build application
        run: yarn dist
      
      # Step 5: Upload the finished product!
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-builder-${{ matrix.os }}
          path: dist/
